//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotStop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stop
    {
        public long Id { get; set; }
        public string StopStart { get; set; }
        public string StopEnd { get; set; }
        public int SideCount { get; set; }
    }
}
